// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools 2015 v1.7.158
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MicrosoftBandTools
{
    static class Vsix
    {
        public const string Id = "74cd5721-9cfd-4183-b1c9-b051f1b59503";
        public const string Name = "Microsoft Band Tools";
        public const string Description = "Provides Intellisense and validation for writing Web Tiles for Microsoft Band 1 & 2";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "band, Intellisense, tiles";
    }
}
